In [65]:
import pandas as pd

# Charger le fichier en désactivant le mode low_memory
df = pd.read_csv('https://raw.githubusercontent.com/ismailoksuz/EAFC26-DataHub/refs/heads/main/data/players.csv', low_memory=False)

In [66]:
df.head()

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,252371,/player/252371/jude-bellingham/260004/,26,4,2025-09-19,J. Bellingham,Jude Victor William Bellingham,"CAM, CM",90,94,...,85+3,85+3,83+3,82+3,81+3,81+3,81+3,82+3,18+3,https://cdn.sofifa.net/players/252/371/26_120.png
1,239053,/player/239053/federico-valverde/260004/,26,4,2025-09-19,F. Valverde,Federico Santiago Valverde Dipetta,"CM, CDM, RB",89,90,...,87+3,87+3,86+3,86+3,83+3,83+3,83+3,86+3,18+3,https://cdn.sofifa.net/players/239/053/26_120.png
2,212622,/player/212622/joshua-kimmich/260004/,26,4,2025-09-19,J. Kimmich,Joshua Walter Kimmich,"CDM, RB, CM",89,89,...,87+2,87+2,86+3,85+3,82+3,82+3,82+3,85+3,21+3,https://cdn.sofifa.net/players/212/622/26_120.png
3,235212,/player/235212/achraf-hakimi/260004/,26,4,2025-09-19,A. Hakimi,Achraf Hakimi Mouhأشرف حكيمي,"RB, RM",89,90,...,83+3,83+3,86+3,86+3,81+3,81+3,81+3,86+3,17+3,https://cdn.sofifa.net/players/235/212/26_120.png
4,224232,/player/224232/nicolo-barella/260004/,26,4,2025-09-19,N. Barella,Nicolò Barella,CM,87,87,...,85+2,85+2,84+3,83+3,80+3,80+3,80+3,83+3,19+3,https://cdn.sofifa.net/players/224/232/26_120.png

In [67]:
df_overall = df[['short_name', 'overall']]

df_overall.head()

      short_name  overall
0  J. Bellingham       90
1    F. Valverde       89
2     J. Kimmich       89
3      A. Hakimi       89
4     N. Barella       87

In [68]:
olise = df_overall['short_name'] == "M. Olise"
df_overall[olise]

    short_name  overall
202   M. Olise       86

In [69]:
df_joueurs = pd.read_csv('C:\\Users\\user\\Projet3\\WorldCup2026\\notebooks\\df_joueurs_niveau_equipe.csv')
df_joueurs.shape

(1215, 22)

In [70]:
df_joueurs.head()

,nom_joueur,equipe_nationale,poste,club_actuel,drapeau_equipe,photo_joueur,buts_marques_par_90,passes_decisives_par_90,xG_buts_attendus_par_90,xA_passes_attendues_par_90,...,buts_hors_penalty_par_90,xG_hors_penalty_par_90,xG_chaine_influence_par_90,xG_chaine_defensive_par_90,niveau_equipe,buts_predits_final,buts_norm,pred_norm,score_final,buts_projectes
0,Fernando Muslera,Uruguay,Gardien,unknown,https://crests.football-data.org/758.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,16.0,0.000000,0.000000,0.000000,0.000000,0.000000
1,Santiago Mele,Uruguay,Gardien,unknown,https://crests.football-data.org/758.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,16.0,0.000000,0.000000,0.000000,0.000000,0.000000
2,Sergio Rochet,Uruguay,Gardien,unknown,https://crests.football-data.org/758.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,16.0,0.000000,0.000000,0.000000,0.000000,0.000000
3,Guillermo Varela,Uruguay,Défenseur,unknown,https://crests.football-data.org/758.svg,https://img.a.transfermarkt.technology/portrai...,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,16.0,0.000000,0.000000,0.000000,0.000000,0.000000
4,Ronald Araújo,Uruguay,Défenseur,Barcelona,https://crests.football-data.org/758.svg,https://img.a.transfermarkt.technology/portrai...,0.171592,0.085796,0.128694,0.042898,...,0.257388,0.128694,0.560728,0.467661,16.0,0.674649,0.126311,0.099695,0.110342,0.607184

In [71]:
# 1. On crée des colonnes temporaires uniquement pour la fusion, sans toucher aux originaux
df_joueurs['key'] = df_joueurs['nom_joueur'].str.split().str[-1]
df_overall['key'] = df_overall['short_name'].str.split().str[-1]

# 2. On fait le merge sur ces clés
df_final = pd.merge(
    df_joueurs, 
    df_overall[['key', 'overall']], # On utilise la clé pour le merge
    on='key', 
    how='left'
)

# 3. On supprime la clé temporaire
df_final = df_final.drop(columns=['key'])

In [72]:
df_final.shape

(4018, 23)

In [73]:
# 1. Filtrer pour ne garder que les joueurs de la France
# Vérifie bien que le nom de la colonne et la valeur correspondent (ex: "France" ou "France")
equipe_france = df_final[df_final['nom_joueur'] == 'Nico Paz']

# 2. Afficher la liste des joueurs
print("Liste des joueurs de l'équipe de France :")
print(equipe_france[['nom_joueur', 'poste', 'overall']])

# 3. Optionnel : Afficher le nombre total de joueurs trouvés
display(f"\nNombre total de joueurs dans l'effectif : {len(equipe_france)}")

df_final.duplicated().sum()

Liste des joueurs de l'équipe de France :
    nom_joueur   poste  overall
704   Nico Paz  Milieu     79.0
705   Nico Paz  Milieu     68.0
706   Nico Paz  Milieu     70.0
707   Nico Paz  Milieu     66.0
708   Nico Paz  Milieu     71.0
709   Nico Paz  Milieu     62.0
710   Nico Paz  Milieu     65.0
711   Nico Paz  Milieu     56.0

"\nNombre total de joueurs dans l'effectif : 8"

np.int64(872)

In [74]:
# 1. On s'assure que 'overall' est bien numérique pour pouvoir trier correctement
df_final['overall'] = pd.to_numeric(df_final['overall'], errors='coerce')

# 2. On trie par 'overall' décroissant (le meilleur en haut)
df_final = df_final.sort_values(by='overall', ascending=False)

# 3. On supprime les doublons en se basant sur le nom complet 
# (on ne splitte plus, on utilise le nom original pour garder la précision)
df_final = df_final.drop_duplicates(subset=['nom_joueur'], keep='first')

# 4. On réinitialise l'index
df_final = df_final.reset_index(drop=True)

In [75]:
df_final.shape

(1213, 23)

In [77]:
df_final.to_csv("df_overall_joueurs.csv")